version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "3500:3500"
    volumes:
      - ./.env:/bin/.env
      - ./tool-manifest.json:/bin/tool-manifest.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3500"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
